package scintillate

object Extensions:
  def guess(ext: String): MediaType = mediaTypes.getOrElse(ext, mediaTypes("bin"))

  val mediaTypes: Map[String, MediaType] = Map(
    "aac"    -> mime"audio/aac",
    "abw"    -> mime"application/x-abiword",
    "arc"    -> mime"application/x-freearc",
    "avi"    -> mime"video/x-msvideo",
    "azw"    -> mime"application/vnd.amazon.ebook",
    "bin"    -> mime"application/octet-stream",
    "bmp"    -> mime"image/bmp",
    "bz"     -> mime"application/x-bzip",
    "bz2"    -> mime"application/x-bzip2",
    "cda"    -> mime"application/x-cdf",
    "csh"    -> mime"application/x-csh",
    "css"    -> mime"text/css",
    "csv"    -> mime"text/csv",
    "doc"    -> mime"application/msword",
    "docx"   -> mime"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "eot"    -> mime"application/vnd.ms-fontobject",
    "epub"   -> mime"application/epub+zip",
    "gz"     -> mime"application/gzip",
    "gif"    -> mime"image/gif",
    "htm"    -> mime"text/html",
    "html"   -> mime"text/html",
    "ico"    -> mime"image/vnd.microsoft.icon",
    "ics"    -> mime"text/calendar",
    "jar"    -> mime"application/java-archive",
    "jpeg"   -> mime"image/jpeg",
    "jpg"    -> mime"image/jpeg",
    "js"     -> mime"text/javascript",
    "json"   -> mime"application/json",
    "jsonld" -> mime"application/ld+json",
    "mid"    -> mime"audio/midi",
    "midi"   -> mime"audio/midi",
    "mjs"    -> mime"text/javascript",
    "mp3"    -> mime"audio/mpeg",
    "mp4"    -> mime"video/mp4",
    "mpeg"   -> mime"video/mpeg",
    "mpkg"   -> mime"application/vnd.apple.installer+xml",
    "odp"    -> mime"application/vnd.oasis.opendocument.presentation",
    "ods"    -> mime"application/vnd.oasis.opendocument.spreadsheet",
    "odt"    -> mime"application/vnd.oasis.opendocument.text",
    "oga"    -> mime"audio/ogg",
    "ogv"    -> mime"video/ogg",
    "ogx"    -> mime"application/ogg",
    "opus"   -> mime"audio/opus",
    "otf"    -> mime"font/otf",
    "png"    -> mime"image/png",
    "pdf"    -> mime"application/pdf",
    "php"    -> mime"application/x-httpd-php",
    "ppt"    -> mime"application/vnd.ms-powerpoint",
    "pptx"   -> mime"application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "rar"    -> mime"application/vnd.rar",
    "rtf"    -> mime"application/rtf",
    "sh"     -> mime"application/x-sh",
    "svg"    -> mime"image/svg+xml",
    "swf"    -> mime"application/x-shockwave-flash",
    "tar"    -> mime"application/x-tar",
    "tif"    -> mime"image/tiff",
    "tiff"   -> mime"image/tiff",
    "ts"     -> mime"video/mp2t",
    "ttf"    -> mime"font/ttf",
    "txt"    -> mime"text/plain",
    "vsd"    -> mime"application/vnd.visio",
    "wav"    -> mime"audio/wav",
    "weba"   -> mime"audio/webm",
    "webm"   -> mime"video/webm",
    "webp"   -> mime"image/webp",
    "woff"   -> mime"font/woff",
    "woff2"  -> mime"font/woff2",
    "xhtml"  -> mime"application/xhtml+xml",
    "xls"    -> mime"application/vnd.ms-excel",
    "xlsx"   -> mime"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "xml"    -> mime"application/xml",
    "xul"    -> mime"application/vnd.mozilla.xul+xml",
    "zip"    -> mime"application/zip",
    "3gp"    -> mime"video/3gpp audio/3gpp",
    "3g2"    -> mime"video/3gpp2 audio/3gpp2",
    "7z"     -> mime"application/x-7z-compressed"
  )