#!/bin/bash
for D in $(find ~/.cache/vex/cls | grep '.class$' | sed 's/.*\/\([^/]*\).class$/\1/' | sort | uniq -c | grep -v ' 1 ' | grep -v '\$' | sed 's/........//')
do
  echo "$D: $(find ~/.cache/vex/cls | grep "\/$D.class" | cut -d/ -f7 | tr '\n' ' ')"
done
