#!/bin/bash

for MOD in mod/*
do
  export ID="$(echo $MOD | cut -d'/' -f2)"
  export TITLE="$(tr '[:lower:]' '[:upper:]' <<< ${ID:0:1})${ID:1}"
  export START="$(git --git-dir mod/$ID/.git  show -s --format=%ci $(git --git-dir mod/$ID/.git rev-list --max-parents=0 HEAD) | cut -d- -f1)"
  export YEAR="$(date "+%y")"
  if [[ "$START" = "$YEAR" ]]; then
    export COPYRIGHT="$START"
  else
    export COPYRIGHT="${START}-$(date +%y)"
  fi
  export VERSION="$(jq '.modules[].version' mod/$ID/build.irk | head -n1 | cut -d'"' -f2)"
  TMP=.tmp.scala
  cat doc/templates/header | envsubst > ${MOD}/.header
  for FILE in ${MOD}/src/**/*.scala
  do
    cat ${MOD}/.header > ${TMP}
    sed '/\(package\|object\|import\)/,$!d' "${FILE}" >> "${TMP}" && mv "${TMP}" "${FILE}"
  done && rm ${MOD}/.header
done
