#!/bin/sh

PWD="$(pwd)"

for x in mod/*
do
  cd $x
  gh label edit duplicate      -d 'An equivalent issue already exists'                      -c '#437a89'
  gh label edit forsaken       -d 'This issue will not be fixed'                            -c '#7d5baf'
  gh label edit severe         -d 'Has a significant impact on many users'                  -c '#b65ea1'
  gh label edit bug            -d 'Describes something not working as intended'             -c '#ef6092'
  gh label edit invalid        -d 'Something does not seem right about this'                -c '#fc6f74'
  gh label edit 'help wanted'  -d 'External assistance is needed'                           -c '#fc8b72'
  gh label edit 'code quality' -d 'Concerns the standard of code rather than functionality' -c '#fca054'
  gh label edit question       -d 'Looking for an answer'                                   -c '#fcb536'
  gh label edit enhancement    -d 'An improvement to existing functionality'                -c '#fcd085'
  gh label edit beginner       -d 'A good introduction for newcomers'                       -c '#e6dd86'
  gh label edit minor          -d 'Has only a small impact for the majority of users'       -c '#d0e993'
  gh label edit release        -d 'Relates to the bureaucracy of releasing the project'     -c '#b2ddbe'
  gh label edit api            -d 'Relates to the API design'                               -c '#93d0e9'
  gh label edit testing        -d 'Concerns how the project is verified'                    -c '#81b6cc'
  gh label edit performance    -d 'Relates to the efficiency or speed of an operation'      -c '#6f9caf'
  gh label edit docs           -d 'Improvements or additions to documentation'              -c '#5d8292'
  gh label edit core           -d 'Describes core required functionality'                   -c '#4a6875'
  cd ../..
done

