#!/bin/bash

for MOD in mod/*
do
  printf "Generating images for $MOD..."
  mkdir -p $MOD/doc/images
  inkscape $MOD/doc/logo.svg --export-filename=$MOD/doc/images/2400x2400@300dpi.png --export-dpi='300' --export-width=2400 --export-height=2400 --export-background-opacity=0 > /dev/null
  printf "."
  inkscape $MOD/doc/logo.svg --export-filename=$MOD/doc/images/1000x1000.png --export-dpi='96' --export-width=1000 --export-height=1000 --export-background-opacity=0 > /dev/null
  printf "."
  convert $MOD/doc/images/1000x1000.png -resize 200x200 $MOD/doc/images/200x200.png > /dev/null
  printf "."
  convert $MOD/doc/images/1000x1000.png -resize 128x128 $MOD/doc/images/128x128.png > /dev/null
  printf "."
  convert $MOD/doc/images/1000x1000.png -resize 48x48 $MOD/doc/images/48x48.png > /dev/null
  printf "."
  convert $MOD/doc/images/1000x1000.png -resize 16x16 $MOD/doc/images/16x16.png > /dev/null
  printf "."
  convert $MOD/doc/images/1000x1000.png -background none -gravity center -resize 620x620 -extent 1280x640 $MOD/doc/images/github.png > /dev/null
  printf "."
  convert $MOD/doc/images/github.png tmpl/github.png -background transparent -layers flatten $MOD/doc/images/github.png > /dev/null
  printf "."
  printf "done\n"
done
