#!/bin/bash

DIR=$PWD

for MOD in mod/*
do
  cd $MOD
  (
    printf "Generating images for $MOD..."
    mkdir -p doc/images
    inkscape doc/logo.svg --export-filename=doc/images/2400x2400@300dpi.png --export-dpi='300' --export-width=2400 --export-height=2400 --export-background-opacity=0 > /dev/null 2>&1
    printf "."
    inkscape doc/logo.svg --export-filename=doc/images/1000x1000.png --export-dpi='96' --export-width=1000 --export-height=1000 --export-background-opacity=0 > /dev/null 2>&1
    printf "."
    convert doc/images/1000x1000.png -resize 200x200 doc/images/200x200.png 2>&1 > /dev/null
    printf "."
    convert doc/images/1000x1000.png -resize 128x128 doc/images/128x128.png 2>&1 > /dev/null
    printf "."
    convert doc/images/1000x1000.png -resize 48x48 doc/images/48x48.png 2>&1 > /dev/null
    printf "."
    convert doc/images/1000x1000.png -resize 16x16 doc/images/16x16.png 2>&1 > /dev/null
    printf "."
    convert doc/images/1000x1000.png -background none -gravity center -resize 620x620 -extent 1280x640 doc/images/github.png > /dev/null
    printf "."
    convert doc/images/github.png ../../tmpl/github.png -background transparent -layers flatten doc/images/github.png > /dev/null
    printf "."
    printf "done\n"
    git add doc/images doc/logo.svg
    git commit -m 'Updated logo'
  )
  cd $DIR
done
