#!/bin/bash

CP="$(ls lib/*.jar | tr '\n' : | head -c-1)"
rm -r classes/*
mkdir -p classes/gesticulate
cp res/gesticulate/media.types classes/gesticulate/media.types
javac -d classes -classpath "$CP" mod/profanity/src/java/**/*.java
scala/bin/scalac "-classpath:$CP:classes" -d classes -deprecation -language:experimental.erasedDefinitions -language:experimental.fewerBraces -language:experimental.saferExceptions -Wunused:all -new-syntax -Yrequire-targetName -Ysafe-init -feature -Ycheck-all-patmat -Yexplicit-nulls \
    mod/acyclicity/src/core/*.scala \
    mod/adversaria/src/core/*.scala \
    mod/caesura/src/core/*.scala \
    mod/cataract/src/core/*.scala \
    mod/clairvoyant/src/css/*.scala \
    mod/clairvoyant/src/html/*.scala \
    mod/clairvoyant/src/http/*.scala \
    mod/contextual/src/core/*.scala \
    mod/cosmopolite/src/core/*.scala \
    mod/escapade/src/core/*.scala \
    mod/escritoire/src/core/*.scala \
    mod/eucalyptus/src/core/*.scala \
    mod/euphemism/src/core/*.scala \
    mod/exoskeleton/src/core/*.scala \
    mod/gastronomy/src/core/*.scala \
    mod/gesticulate/src/core/*.scala \
    mod/gossamer/src/core/*.scala \
    mod/guillotine/src/core/*.scala \
    mod/honeycomb/src/core/*.scala \
    mod/iridescence/src/core/*.scala \
    mod/jovian/src/core/*.scala \
    mod/kaleidoscope/src/core/*.scala \
    mod/probably/src/core/*.scala \
    mod/probably/src/cli/*.scala \
    mod/probably/src/tolerance/*.scala \
    mod/punctuation/src/core/*.scala \
    mod/punctuation/src/ansi/*.scala \
    mod/punctuation/src/html/*.scala \
    mod/profanity/src/core/*.scala \
    mod/rudiments/src/core/*.scala \
    mod/scintillate/src/core/*.scala \
    mod/scintillate/src/server/*.scala \
    mod/scintillate/src/servlet/*.scala \
    mod/slalom/src/core/*.scala \
    mod/tarantula/src/core/*.scala \
    mod/wisteria/src/core/*.scala \
    mod/xylophone/src/core/*.scala \
    && cd classes && jar cf ../niveau.jar $(ls)
