#!/bin/bash

CP="stbin:$(ls lib/*.jar | tr '\n' : | head -c-1)"
rm -r classes/*
mkdir -p classes/gesticulate
cp res/gesticulate/media.types classes/gesticulate/media.types
javac -d classes -classpath "$CP" mod/profanity/src/java/**/*.java
#etc/stacktraces

jar cf lib/mediatypes.jar -C res gesticulate
jar cf lib/profanity-java.jar -C classes profanity

scli compile \
    -S 3.1.1-RC1-bin-SNAPSHOT \
    -d org.typelevel:jawn-parser_3:1.2.0 \
    -d org.typelevel:jawn-ast_3:1.2.0 \
    -d com.vladsch.flexmark:flexmark:0.62.2 \
    -d com.vladsch.flexmark:flexmark-ext-tables:0.62.2 \
    -d com.vladsch.flexmark:flexmark-ext-typographic:0.62.2 \
    -d javax.servlet:javax.servlet-api:3.0.1 \
    -d net.java.dev.jna:jna:5.10.0 \
    --progress \
    --home . \
    --jar lib/mediatypes.jar \
    --jar lib/profanity-java.jar \
    -language:experimental.erasedDefinitions \
    -language:experimental.fewerBraces \
    -language:experimental.saferExceptions \
    -Wunused:all \
    -O -deprecation \
    -O -feature \
    -O -new-syntax \
    -Yrequire-targetName \
    -Ysafe-init \
    -Ycheck-all-patmat \
    -Yexplicit-nulls \
    $@ \
    mod/acyclicity/src/core/*.scala \
    mod/adversaria/src/core/*.scala \
    mod/caesura/src/core/*.scala \
    mod/cataract/src/core/*.scala \
    mod/clairvoyant/src/css/*.scala \
    mod/clairvoyant/src/html/*.scala \
    mod/clairvoyant/src/http/*.scala \
    mod/contextual/src/core/*.scala \
    mod/cosmopolite/src/core/*.scala \
    mod/escapade/src/core/*.scala \
    mod/escritoire/src/core/*.scala \
    mod/eucalyptus/src/core/*.scala \
    mod/euphemism/src/core/*.scala \
    mod/exoskeleton/src/core/*.scala \
    mod/gastronomy/src/core/*.scala \
    mod/gesticulate/src/core/*.scala \
    mod/gossamer/src/core/*.scala \
    mod/guillotine/src/core/*.scala \
    mod/harlequin/src/core/*.scala \
    mod/honeycomb/src/core/*.scala \
    mod/iridescence/src/core/*.scala \
    mod/jovian/src/core/*.scala \
    mod/kaleidoscope/src/core/*.scala \
    mod/probably/src/core/*.scala \
    mod/probably/src/cli/*.scala \
    mod/probably/src/tolerance/*.scala \
    mod/punctuation/src/core/*.scala \
    mod/punctuation/src/ansi/*.scala \
    mod/punctuation/src/html/*.scala \
    mod/profanity/src/core/*.scala \
    mod/rudiments/src/core/*.scala \
    mod/scintillate/src/core/*.scala \
    mod/scintillate/src/server/*.scala \
    mod/scintillate/src/servlet/*.scala \
    mod/slalom/src/core/*.scala \
    mod/tarantula/src/core/*.scala \
    mod/wisteria/src/core/*.scala \
    mod/xylophone/src/core/*.scala
#&& cd classes && jar cf ../niveau.jar $(ls)
