#!/bin/zsh

for MOD in mod/*
do
  cd "$MOD" || exit
  BRANCH="$(git rev-parse --abbrev-ref HEAD)"
  if [ "${BRANCH}" != "main" ]
  then
    echo -e "\e[35m${MOD:4}\e[0m is on branch \e[33m${BRANCH}\e[0m"
  fi
  for BRANCH in $(git branch | grep -v "${BRANCH}" | grep -v "issue-")
  do
    echo -e "\e[35m${MOD:4}\e[0m has additional branch \e[34m${BRANCH}\e[0m"
  done
  git branch | grep 'issue-' > /dev/null && echo -e "\e[35m${MOD:4}:\e[0m"
  for ISSUE in $(git branch | grep 'issue-' | cut -d- -f2)
  do
    echo -e "  \e[34missue-$ISSUE\e[0m:$(gh issue view "$ISSUE" | head -n1 | cut -d: -f2 | tr '\t' ' ')"
  done
  git branch | grep 'issue-' > /dev/null && echo
  git diff-index --quiet HEAD -- || echo -e "\e[35m${MOD:4}\e[0m has \e[36muncommitted changes\e[0m"
  cd ../..
done
