#!/bin/sh

echo toString uses:
grep -r 'toString' mod/*/src/*/*.scala | sed 's/^/    /'
echo
echo 'asInstanceOf uses:'
grep -r 'asInstanceOf' mod/*/src/*/*.scala | sed 's/^/    /'
echo
echo 'println uses:'
grep -r 'println' mod/*/src/*/*.scala | sed 's/^/    /'
echo
