#!/bin/bash

declare portFile initFile ttystate script waitFile tmpPipe javaVersion dataHomeDir arch os data stderr
declare -i pid port version buildId stdoutPid continue pipePid argCount launchPid
declare -a args signals sttyOptions

# The TTY settings to use for terminal input
sttyOptions=(intr undef -echo icanon raw opost)

name="$(basename $0)"
baseDir="${XDG_RUNTIME_DIR:-$HOME/.local/state}/$name"
dataHomeDir="${XDG_DATA_HOME:-$HOME/.local/share}"
portFile="$baseDir/port"
initFile="$baseDir/init"
waitFile="$baseDir/wait"
failFile="$baseDir/fail"
script="$(realpath "$0")"
javaVersion="21"
javaHome="$dataHomeDir/java/$javaVersion"
continue=1

# The set of signals which should be captured and forwarded to the JVM process
signals=(INT WINCH TERM)

pid=$$
args=("$@")
argCount=$#

backOut() {
  if [ -f "$failFile" ]
  then
    test -t 0 && stty "$ttystate"
    printf "The daemon process failed to start.\n" >&2
    printf "Remove the file %s before trying again.\n" "$failFile" >&2
    exit 1
  fi
}

ensure() {
  command -v "$1" > /dev/null || printf "The command %s is required, but was not found. Please install %s and try again.\n" "$1" "$2" 1>&2
  command -v "$1" > /dev/null || exit 1
}

installJava() {
  local dir
  mkdir -p "$dataHomeDir/java"
  ensure unzip Unzip
  
  case "$(uname -s)" in
    Linux|GNU*)       os="linux" ;;
    Win*|Cygwin|Msys) os="windows" ;;
    Mac*|Darwin*)     os="mac" ;;
    SunOS)            os="solaris" ;;
    *)                exit 1 ;;
  esac

  case "$(uname -m)" in
    x86_64|amd64|i686-64)                   arch="x64" ;;
    x86|i686|i386|i86pc)                    arch="x86" ;;
    aarch64_be|aarch64|armv8b|armv8l|arm64) arch="aarch64" ;;
    *)                                      exit 1 ;;
  esac

  unzip -p "$script" "spectral/jre-$javaVersion-$os-$arch.tar.gz" 2>/dev/null | tar xzf - -C "$dataHomeDir/java"
  dir=$(unzip -p "$script" "spectral/jre-$javaVersion-$os-$arch.tar.gz" 2>/dev/null | tar tzf - | head -n1)
  mv "$dataHomeDir/java/$dir" "$javaHome"
}

abort() {
  touch "$failFile"
  printf '' > "$waitFile"
  rm -f "$waitFile" "$initFile"
}

launch() {
  test -x "$javaHome/bin/java" || installJava
  mkfifo "$waitFile" 2> /dev/null && (exec nohup "$javaHome/bin/java" -Dspectral.name="$name" -Dspectral.script="$script" -Dspectral.command="$(command -v "$name")" -Dspectral.fpath="$(zsh -c 'printf "%s\n" $fpath' 2> /dev/null || echo '')" -jar "$script" > /dev/null 2>&1 || abort) &
  launchPid=$!
  ensure flock Flock
  flock "$initFile" sh -c "test -f \"$portFile\" || cat \"$waitFile\"" > /dev/null 2>&1 || abort
  rm -f "$initFile"
  data="$(<"$portFile")"
  port=${data%% *}
}

handle() {
  case "$1" in
    TERM) continue=0 ;;
  esac
  printf "s\n%s\n%s\n" "$pid" "$1" | nc -q0 localhost $port
}

terminate() {
  exit "$(printf "x\n%s\n" "$pid" | nc -q0 localhost $port)" >/dev/null 2>&1
}

connect() {
  test -t 0 && printf "i\nt\n" || printf "i\np\n"
  printf "%s\n%s\n" "$pid" "$script"
  pwd
  printf "%s\n" "$argCount"
  printf '%s\0' "${args[@]}"
  printf "\n##\n"
  env -0
  printf "\n##\n"
  exec cat
}

connectStderr() {
  printf "e\n%s" "$pid"
}

test -t 0 && ttystate="$(stty -g)"
mkdir -p "$baseDir"
backOut

flock -n "$portFile" rm "$portFile"

if [ -f "$portFile" ]
then
  data="$(<"$portFile")"
  port=${data%% *}
  data2="${data#* }"
  stderr=${data2#* }
  version=${data2% *}
  buildId=%%BUILDID%%
  
  if [ $version -ne $buildId ]
  then
    rm -f "$portFile"
    sleep 0.1
  fi
fi

test -f "$portFile" || launch
backOut

ensure nc Netcat
ensure ps Procps

tmpPipe="$(mktemp -u)"
mkfifo -m 600 "$tmpPipe" && exec 3<> "$tmpPipe" && rm "$tmpPipe"
test -t 0 && stty "${sttyOptions[@]}" > /dev/null 2>&1
connect <&0 >&3 &
stdoutPid=$!
nc -q0 localhost $port <&3 &
pipePid=$!

for signal in "${signals[@]}"
do trap "handle $signal" "$signal"
done

while [ $continue = 1 ]
do
  wait $pipePid
  ps $pipePid > /dev/null || continue=0
done

test -t 0 && stty "$ttystate"
kill $stdoutPid $launchPid >/dev/null 2>&1
terminate
exit 1
