#!/bin/bash

declare portFile initFile ttystate script waitFile tmpPipe javaVersion dataHomeDir arch os data stderr
declare -i pid port version buildId stdoutPid continue pipePid argCount launchPid
declare -a args signals sttyOptions

# The TTY settings to use for terminal input
sttyOptions=(intr undef -echo icanon raw opost)

name="$(basename $0)"
baseDir="${XDG_RUNTIME_DIR:-$HOME/.local/state}/$name"
dataHomeDir="${XDG_DATA_HOME:-$HOME/.local/share}"
portFile="$baseDir/port"
initFile="$baseDir/init"
waitFile="$baseDir/wait"
failFile="$baseDir/fail"
script="$(realpath "$0")"
javaVersion="21"
javaHome="$dataHomeDir/java/$javaVersion"
continue=1

# The set of signals which should be captured and forwarded to the JVM process
signals=(INT WINCH TERM)

pid=$$
args=("$@")
argCount=$#

backOut() {
  if [ -f "$failFile" ]
  then
    test -t 0 && stty "$ttystate"
    printf "The daemon process failed to start.\n" >&2
    printf "Remove the file %s before trying again.\n" "$failFile" >&2
    exit 1
  fi
}

abort() {
  touch "$failFile"
  printf '' > "$waitFile"
  rm -f "$waitFile" "$initFile"
}

launch() {
  test -x "$javaHome/bin/java" || extract
  mkfifo "$waitFile" 2> /dev/null && (exec nohup "$javaHome/bin/java" -Dspectral.name="$name" -Dspectral.script="$script" -Dspectral.command="$(command -v "$name")" -Dspectral.fpath="$(zsh -c 'printf "%s\n" $fpath' 2> /dev/null || echo '')" -jar "$script" > /dev/null 2>&1 || abort) &
  launchPid=$!
  flock "$initFile" sh -c "test -f \"$portFile\" || cat \"$waitFile\"" > /dev/null 2>&1 || abort
  rm -f "$initFile"
  data="$(<"$portFile")"
  port=${data%% *}
}

handle() {
  case "$1" in
    TERM) continue=0 ;;
  esac
  printf "s\n%s\n%s\n" "$pid" "$1" >/dev/tcp/localhost/$port
}

extract() {
  local -i offset
  local dir
  mkdir -p "$dataHomeDir/java"
  offset=$(grep -aobm1 'TERMINUS$' "$script" | cut -d: -f1)
  tail -c +$((offset+10)) $script | tar xz -C "$dataHomeDir/java" 2> /dev/null
  dir="$(tail -c +$((offset+10)) $script | tar tzf - 2> /dev/null | head -n1)"
  mv "$dataHomeDir/java/$dir" "$javaHome"
}

terminate() {
  exec 6<> /dev/tcp/localhost/$port
  printf "x\n%s\n" "$pid" >&6
  exit "$(cat <&6)"
}

connectStderr() {
  printf "e\n%s" "$pid"
}

test -t 0 && ttystate="$(stty -g)"
mkdir -p "$baseDir"
backOut

flock -n "$portFile" rm "$portFile"

if [ -f "$portFile" ]
then
  data="$(<"$portFile")"
  port=${data%% *}
  data2="${data#* }"
  stderr=${data2#* }
  version=${data2% *}
  buildId=%%BUILDID%%
  
  if [ $version -ne $buildId ]
  then
    rm -f "$portFile"
    sleep 0.1
  fi
fi

test -f "$portFile" || launch
backOut

tmpPipe="$(mktemp -u)"
mkfifo -m 600 "$tmpPipe" && exec 3<> "$tmpPipe" && rm "$tmpPipe"
test -t 0 && stty "${sttyOptions[@]}" > /dev/null 2>&1
exec 7<> /dev/tcp/localhost/$port

test -t 0 && printf "i\nt\n" >&7 || printf "i\np\n" >&7
printf "%s\n%s\n" "$pid" "$script" >&7
pwd >&7
printf "%s\n" "$argCount" >&7
printf '%s\0' "${args[@]}" >&7
printf "\n##\n" >&7
env -0 >&7
printf "\n##\n" >&7
cat >&7 <&0 &
stdoutPid=$!
cat <&7 &
pipePid=$!

for signal in "${signals[@]}"
do trap "handle $signal" "$signal"
done

while [ $continue = 1 ]
do
  wait $pipePid
  kill -0 $pipePid 2> /dev/null || continue=0
done

test -t 0 && stty "$ttystate"
kill $launchPid $stdoutPid 2> /dev/null
terminate
exit 1

: TERMINUS
