                                                                                                  /*
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                  ┃
┃                                                   ╭───╮                                          ┃
┃                                                   │   │                                          ┃
┃                                                   │   │                                          ┃
┃   ╭───────╮╭─────────╮╭───╮ ╭───╮╭───╮╌────╮╭────╌┤   │╭───╮╌────╮╭────────╮╭───────╮╭───────╮   ┃
┃   │   ╭───╯│   ╭─╮   ││   │ │   ││   ╭─╮   ││   ╭─╮   ││   ╭─╮   ││   ╭─╮  ││   ╭───╯│   ╭───╯   ┃
┃   │   ╰───╮│   │ │   ││   │ │   ││   │ │   ││   │ │   ││   │ │   ││   ╰─╯  ││   ╰───╮│   ╰───╮   ┃
┃   ╰───╮   ││   │ │   ││   │ │   ││   │ │   ││   │ │   ││   │ │   ││   ╭────╯╰───╮   │╰───╮   │   ┃
┃   ╭───╯   ││   ╰─╯   ││   ╰─╯   ││   │ │   ││   ╰─╯   ││   │ │   ││   ╰────╮╭───╯   │╭───╯   │   ┃
┃   ╰───────╯╰─────────╯╰────╌╰───╯╰───╯ ╰───╯╰────╌╰───╯╰───╯ ╰───╯╰────────╯╰───────╯╰───────╯   ┃
┃                                                                                                  ┃
┃    Soundness, version 0.54.0.                                                                    ┃
┃    © Copyright 2021-25 Jon Pretty, Propensive OÜ.                                                ┃
┃                                                                                                  ┃
┃    The primary distribution site is:                                                             ┃
┃                                                                                                  ┃
┃        https://soundness.dev/                                                                    ┃
┃                                                                                                  ┃
┃    Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file     ┃
┃    except in compliance with the License. You may obtain a copy of the License at                ┃
┃                                                                                                  ┃
┃        https://www.apache.org/licenses/LICENSE-2.0                                               ┃
┃                                                                                                  ┃
┃    Unless required by applicable law or agreed to in writing,  software distributed under the    ┃
┃    License is distributed on an "AS IS" BASIS,  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,    ┃
┃    either express or implied. See the License for the specific language governing permissions    ┃
┃    and limitations under the License.                                                            ┃
┃                                                                                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
                                                                                                  */
package exegesis

import anticipation.*
import beneficence.*
import jacinta.*
import obligatory.*
import vacuous.*

// The methods a Language Server may call back on its client. As with synesthesia's `McpClient`,
// these are the server-to-client half of the protocol; the implementation is generated by the
// `JsonRpc` `client` macro. Only notifications are exposed (no requests), since a request handler
// runs on the same thread that reads the client's responses, and a synchronous round-trip from
// within a handler would deadlock.
trait LspClient extends Findable:
  import Lsp.*

  @rpc
  protected def `textDocument/publishDiagnostics`
    ( uri: Text, version: Optional[Int], diagnostics: List[Diagnostic] )
  :   Unit

  @rpc
  protected def `window/showMessage`(`type`: MessageType, message: Text): Unit

  @rpc
  protected def `window/logMessage`(`type`: MessageType, message: Text): Unit

  @rpc
  protected def `telemetry/event`(params: Json): Unit

  @rpc
  protected def `$/logTrace`(message: Text, verbose: Optional[Text]): Unit

  // A `ProgressToken` is a string or integer, and a progress `value` is protocol-specific, so both
  // are passed as raw JSON.
  @rpc
  protected def `$/progress`(token: Json, value: Json): Unit

  @rpc
  protected def `$/cancelRequest`(id: Json): Unit

  def publishDiagnostics(uri: Text, diagnostics: List[Diagnostic]): Unit =
    `textDocument/publishDiagnostics`(uri, Unset, diagnostics)

  def showMessage(message: Text): Unit = `window/showMessage`(MessageType.Info, message)
  def logMessage(message: Text): Unit = `window/logMessage`(MessageType.Log, message)
  def telemetry(params: Json): Unit = `telemetry/event`(params)
  def logTrace(message: Text): Unit = `$/logTrace`(message, Unset)
  def progress(token: Json, value: Json): Unit = `$/progress`(token, value)
  def cancelRequest(id: Json): Unit = `$/cancelRequest`(id)
