// Generated by `wit-bindgen scala tests/wasm/wit --world http` (the scala-wasm fork), then reduced
// to the export surface as the `e2e` world's bindings are: the generator also emits facade classes
// for all ten imported interfaces, but none is used, because telekinesis' `WasiHttpServer` reaches
// the `wasi:http` resources through xenophile's `invoke` — which emits `witImportCall` against the
// interface's own WIT contract — rather than through generated Scala facades.
//
// The two parameter types must be scala-wasm's own facade classes, not local redeclarations: the
// linker emits a cast of each incoming resource handle to the canonical facade for its WIT resource
// (`scala.scalajs.wasi.http.types.IncomingRequest`), so a same-shaped trait declared here traps at
// run time with `wasm trap: cast failure` before the handler is ever entered.
package componentmodel.exports.wasi.http

import scala.scalajs.wasi.http.types.{IncomingRequest, ResponseOutparam}

// Export interface
@scala.scalajs.wit.annotation.WitExportInterface
trait IncomingHandler:
  @scala.scalajs.wit.annotation.WitExport("wasi:http/incoming-handler@0.2.0", "handle")
  def handle(request: IncomingRequest, responseOut: ResponseOutparam): Unit
