// Generated by `wit-bindgen scala tests/wasm/wit --world http` (the scala-wasm fork), then reduced
// to the export surface as the `e2e` world's bindings are: the generator also emits facade classes
// for all ten imported interfaces, but none is used, because telekinesis' `WasiHttpServer` reaches
// the `wasi:http` resources through xenophile's `invoke` — which emits `witImportCall` against the
// interface's own WIT contract — rather than through generated Scala facades.
//
// The two parameter types are substituted for scala-wasm's own facade classes, and that
// substitution is load-bearing — it works around a bug in the generator. For an exported function
// taking an imported resource, `wit-bindgen scala` types the parameter as its *own* generated
// facade (`componentmodel.wasi.http.types.IncomingRequest`), while the backend emits a cast of the
// incoming handle to the canonical one (`scala.scalajs.wasi.http.types.IncomingRequest`). The two
// are unrelated types, so the guest traps before the handler is entered:
//
//     wasm trap: cast failure
//     0: as.scala.scalajs.wasi.http.types.package$IncomingRequest
//     1: f.e2ehttp.Service$.handle;Lcomponentmodel.wasi.http.types.package$IncomingRequest;…
//     2: wasi:http/incoming-handler@0.2.0#handle
//
// Verified against the generator's unmodified output (2026-08-04, wit-bindgen-cli 0.50.0,
// wasmtime 46.0.1): to reproduce, generate with `--world http`, compile the emitted
// `componentmodel/` tree as-is, and serve it — it links cleanly and traps on the first request.
// Naming `scala.scalajs.wasi.…` here is the fix until the generator does.
package componentmodel.exports.wasi.http

import scala.scalajs.wasi.http.types.{IncomingRequest, ResponseOutparam}

// Export interface
@scala.scalajs.wit.annotation.WitExportInterface
trait IncomingHandler:
  @scala.scalajs.wit.annotation.WitExport("wasi:http/incoming-handler@0.2.0", "handle")
  def handle(request: IncomingRequest, responseOut: ResponseOutparam): Unit
