// Generated by `wit-bindgen scala tests/wasm/wit` (the scala-wasm fork) for the `e2e` world,
// then checked in: the output is stable for a fixed world, and checking it in keeps the
// component's export surface reviewable and inside the CI input digest.
package componentmodel.exports.wasi.cli

package object run {

}

// Export interface
@scala.scalajs.wit.annotation.WitExportInterface
trait Run {

  // Functions
  /** Run the program.
   */
  @scala.scalajs.wit.annotation.WitExport("wasi:cli/run@0.2.0", "run")
  def run(): scala.scalajs.wit.Result[Unit, Unit]

}
