package quantify

val Galileo = SiUnit(0.01*Metre/(Second*Second))
val Poise = SiUnit(0.1*Pascal)
val Franklin = SiUnit(3.34e-10*Coulomb)
val Biot = SiUnit(10*Ampere)
val Debye = SiUnit(3.335e-30*Coulomb*Metre)
val Erg = SiUnit(10e-7*Joule)
val Dyne = SiUnit(10e-5*Newton)
val Calorie = SiUnit(4.184*Joule)
val Langley = SiUnit(41840*Joule/(Metre*Metre))
val Phot = SiUnit(10e4*Lux)
val Stokes = SiUnit(10e-4*Metre*Metre/Second)
val Lambert = SiUnit((10e4/math.Pi)*Candela/(Metre*Metre))
val Emu = SiUnit(10e-3*Ampere/(Metre*Metre))
val Oersted = SiUnit(79.577*Ampere/Metre)
val Maxwell = SiUnit(10e-8*Weber)
val Gauss = SiUnit(10e-4*Tesla)
val Gilbert = SiUnit(0.796*Ampere)
val Darcy = SiUnit(0.987e-12*Metre*Metre)
val Barye = SiUnit(0.1*Pascal)
val Kayser = SiUnit(100/Second)