#!/bin/sh

SCRIPTDIR="$(cd -- "$(dirname -- "$0")" > /dev/null 2>&1 && pwd)"
THIS="$(basename "$0")"
ARGS="$(printf '%s\t' "$@")"
ARGCOUNT="$#"
PID="$$"
RUNDIR="${XDG_RUNTIME_DIR:-${TMPDIR:-${SCRIPTDIR}/.cache}}"
MDATE="$(date -r "$0" +%s)"
FIFO="$RUNDIR/$THIS-$MDATE.sock"
STDOUT="$RUNDIR/$THIS-$PID.stdout.sock"
STDIN="$RUNDIR/$THIS-$PID.stdin.sock"
EXITFILE="$RUNDIR/$THIS-$PID.exit"

server() {
  if [ ! -d "$RUNDIR" ]; then
    mkdir -p "$RUNDIR"
  fi
  mkfifo "$FIFO"
  (while true; do sleep 3600; done) > "$FIFO" &
  CATPID="$!"
  exec java \
      -Dsun.misc.URLClassPath.disableJarChecking \
      -Dexoskeleton.script="$THIS" \
      -Dexoskeleton.fifo="$FIFO" \
      -Dexoskeleton.pid="$PID" \
      -Dexoskeleton.watch="$CATPID" \
      -jar "$SCRIPTDIR/$THIS" &
}

connect() {
  mkfifo "$STDOUT" "$STDIN" "$EXITFILE"
  echo "PROCESS	$PID" > "$FIFO"
  echo "SCRIPT	$PID	$SCRIPTDIR	$THIS" > "$FIFO"
  echo "RUNDIR	$PID	$RUNDIR" > "$FIFO"
  echo "ARGS	$PID	$ARGCOUNT	$ARGS" > "$FIFO"
  echo "ENV	$PID	$(env | tr '\n' '\t')" > "$FIFO"
  echo "START	$PID" > "$FIFO"
  cat - 2> /dev/null > "$STDIN" <&0 &
  CATPID="$!"
  cat "$STDOUT" &
  WRITERPID="$!"
  EXIT="$(cat "$EXITFILE")"
  
  if [ "$EXIT" = "99" ]
  then
    stty -echo -icanon -isig min 1 time 0
    EXIT="$(cat "$EXITFILE")"
  fi
  
  kill "$CATPID" > /dev/null 2>&1
  rm -f "$STDOUT" "$STDIN" "$EXITFILE"
  stty sane
  exit "${EXIT:-1}"
}

resize() {
  echo "RESIZE	$PID" > "$FIFO"
}

cleanup() {
  stty sane
  printf "\e[0J\e[?25h"
}

trap cleanup EXIT
trap resize WINCH

if [ ! -p "$FIFO" ]
then
  server
else
  if [ -f "$FIFO" ]
  then
    echo "Cannot create named pipe at $FIFO"
    exit 1
  fi
fi
connect
exit 1
